(function(){"use strict";var entity=document.body.dataset.entity;var api='/api/'+entity;var form=document.getElementById('entityForm');var rows=document.getElementById('rows');var message=document.getElementById('message');var cancel=document.getElementById('cancelEdit');var cache=[];
function text(v){return v==null?'':String(v)}function escape(v){var d=document.createElement('div');d.textContent=text(v);return d.innerHTML}async function error(r){try{var x=await r.json();return x.message||x.Message||JSON.stringify(x)}catch(_){return 'Request failed ('+r.status+').' }}
function field(id){return document.getElementById(id)}function payload(){return entity==='customers'?{name:field('name').value.trim(),phone:field('phone').value.trim(),address:field('address').value.trim()}:{name:field('name').value.trim(),unitPrice:Number(field('unitPrice').value)}}
function reset(){form.reset();field('editId').value='';cancel.hidden=true}
function render(){rows.innerHTML=cache.map(function(x){var cells=entity==='customers'?'<td>'+escape(x.phone)+'</td><td>'+escape(x.address)+'</td>':'<td>'+Number(x.unitPrice).toFixed(2)+'</td><td>'+new Date(x.createdAtUtc).toLocaleDateString()+'</td>';return '<tr><td>'+x.id+'</td><td>'+escape(x.name)+'</td>'+cells+'<td><div class="actions"><button data-edit="'+x.id+'">Edit</button><button class="danger" data-delete="'+x.id+'">Delete</button></div></td></tr>'}).join('')}
function productQuery(){if(entity!=='products')return '';var p=new URLSearchParams();[['filterId','Id'],['filterName','Name'],['filterMin','MinUnitPrice'],['filterMax','MaxUnitPrice']].forEach(function(x){var v=field(x[0]).value.trim();if(v)p.set(x[1],v)});return '/filter?'+p.toString()}
async function load(){try{var r=await fetch(api+productQuery());if(!r.ok)throw new Error(await error(r));cache=await r.json();render();message.textContent=cache.length+' record(s) loaded.'}catch(e){message.textContent=e.message}}
form.addEventListener('submit',async function(e){e.preventDefault();var id=field('editId').value;try{var r=await fetch(api+(id?'/'+id:''),{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});if(!r.ok)throw new Error(await error(r));reset();await load();message.textContent=id?'Updated successfully.':'Created successfully.'}catch(ex){message.textContent=ex.message}});
rows.addEventListener('click',async function(e){var edit=e.target.dataset.edit;var del=e.target.dataset.delete;if(edit){var x=cache.find(function(a){return a.id===Number(edit)});field('editId').value=x.id;field('name').value=x.name;if(entity==='customers'){field('phone').value=x.phone;field('address').value=x.address||''}else field('unitPrice').value=x.unitPrice;cancel.hidden=false;scrollTo({top:0,behavior:'smooth'})}if(del&&confirm('Delete this record?')){try{var r=await fetch(api+'/'+del,{method:'DELETE'});if(!r.ok)throw new Error(await error(r));await load();message.textContent='Deleted successfully.'}catch(ex){message.textContent=ex.message}}});cancel.addEventListener('click',reset);if(entity==='products'){field('productFilterForm').addEventListener('submit',function(e){e.preventDefault();load()});field('clearFilters').addEventListener('click',function(){field('productFilterForm').reset();load()})}load()})();
