using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Http;
using EnterpriseInvoiceSystem.Services;
using EnterpriseInvoiceSystem.DTOs;

namespace EnterpriseInvoiceSystem.Controllers
{
    // Groups the invoice reporting endpoints under one common URL prefix.
    [RoutePrefix("api/reports/invoices")]
    public class ReportsController : ApiController
    {
        // Loads the invoice data shared by both the data and PDF endpoints.
        readonly InvoiceService invoiceService = new InvoiceService();

        // Converts invoice data into a Crystal Reports PDF document.
        readonly CrystalReportService crystalReportService = new CrystalReportService();
        readonly ProductService productService = new ProductService();

        [HttpGet, Route("~/api/reports/products/pdf")]
        public async Task<HttpResponseMessage> ProductPdf([FromUri] ProductFilterRequest request)
        {
            var products = await productService.FilterAsync(request ?? new ProductFilterRequest());
            var response = new HttpResponseMessage(HttpStatusCode.OK) { Content = new ByteArrayContent(crystalReportService.GenerateProductPdf(products)) };
            response.Content.Headers.ContentType = new MediaTypeHeaderValue("application/pdf");
            response.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment") { FileName = "Products.pdf" };
            return response;
        }

        // Returns the report-ready invoice data so clients can inspect or render it themselves.
        [HttpGet, Route("{id:int}/data")]
        public async Task<IHttpActionResult> Data(int id)
        {
            // Await the asynchronous lookup without blocking the request-handling thread.
            var invoiceReport = await invoiceService.GetReportAsync(id);

            // A missing invoice maps to HTTP 404; otherwise return its data with HTTP 200.
            return invoiceReport == null ? (IHttpActionResult)NotFound() : Ok(invoiceReport);
        }

        // Generates and downloads a PDF for the requested invoice.
        [HttpGet, Route("{id:int}/pdf")]
        public async Task<IHttpActionResult> Pdf(int id, bool inline = false)
        {
            // Load the same report-ready model that is used by the data endpoint.
            var invoiceReport = await invoiceService.GetReportAsync(id);

            // Stop before PDF generation when the requested invoice does not exist.
            if (invoiceReport == null)
                return NotFound();

            try
            {
                // Bind the invoice model to the Crystal Report and export it as PDF bytes.
                var pdfBytes = crystalReportService.GenerateInvoicePdf(invoiceReport);

                // Wrap the generated bytes in a successful HTTP response.
                var response = new HttpResponseMessage(HttpStatusCode.OK)
                {
                    Content = new ByteArrayContent(pdfBytes),
                };

                // Tell clients that the response body contains a PDF document.
                response.Content.Headers.ContentType = new MediaTypeHeaderValue("application/pdf");

                // Preserve download behavior by default; the frontend can request inline preview.
                response.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue(
                    inline ? "inline" : "attachment"
                )
                {
                    FileName = "Invoice_" + Safe(invoiceReport.InvoiceNumber) + ".pdf",
                };

                // Adapt HttpResponseMessage to the IHttpActionResult expected by Web API.
                return ResponseMessage(response);
            }
            catch (FileNotFoundException ex)
            {
                // Preserve the useful missing-file detail for deployment/configuration diagnosis.
                return Content(
                    HttpStatusCode.InternalServerError,
                    new { message = "Invoice PDF generation failed.", detail = ex.Message }
                );
            }
            catch (Exception)
            {
                // Avoid exposing unexpected internal exception details to API consumers.
                return Content(
                    HttpStatusCode.InternalServerError,
                    new
                    {
                        message = "Invoice PDF generation failed.",
                        detail = "Crystal Reports could not load, bind, or export the report.",
                    }
                );
            }
        }

        // Replaces characters that are invalid in filenames so the invoice number is safe to use.
        static string Safe(string value)
        {
            // Use the platform's invalid-character list instead of maintaining a partial list here.
            var invalidFileNameCharacters = Path.GetInvalidFileNameChars();

            // Keep valid characters and replace every invalid one with an underscore.
            return new string(
                value
                    .Select(character =>
                        invalidFileNameCharacters.Contains(character) ? '_' : character
                    )
                    .ToArray()
            );
        }
    }
}
